# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Build and Load

on:
  workflow_call:
    inputs:
      bake_target:
        required: true
        type: string
        description: "Bake target to build and load"
      image_repo:
        required: true
        type: string
        description: "Image repo to use."
      image_tag:
        required: true
        type: string
        description: "Image tag to use."

jobs:
  build-and-load:
    name: Build and Load
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Login to ghcr.io
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: notused
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Cache Docker layers
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ inputs.bake_target }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.bake_target }}-buildx-

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: |
            ${{ inputs.image_repo }}/${{ inputs.bake_target }},enable=true
          tags: | 
            type=raw,value=${{ inputs.image_tag }}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Create cache and artifacts directories
        run: |
          mkdir /tmp/artifacts

      - name: Build
        uses: docker/bake-action@3acf805d94d93a86cce4ca44798a76464a75b88c # v6.9.0
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.metadata.outputs.bake-file }}
          targets: ${{ inputs.bake_target }}
          provenance: false
          set: |
            *.platform=linux/amd64
            *.output=type=docker,dest=/tmp/artifacts/${{ inputs.bake_target }}.tar
            *.cache-from=type=local,src=/tmp/.buildx-cache
        env:
          IMAGE_REPO: ${{ inputs.image_repo }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          DOCKER_BUILD_RECORD_UPLOAD: false

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ inputs.bake_target }}
          path: /tmp/artifacts/${{ inputs.bake_target }}.tar
          retention-days: 1
